Module11 task1
htmlacademy-javascript/1110353-kekstagram-25 pull request #9
Opened 2022-04-08 17:55 UTC by AnastasiaRakh3

2022-04-09 09:20 UTC, vitali-usik requested changes

2022-04-09 09:20 UTC, vitali-usik commented on js/form-init.js
> +const imgFormClose = imgForm.querySelector('.img-upload__cancel');
В переменных, которые содержат в себе ссылку на DOM элемент можно добавить постфикс `Element`. Например `imgFormSubmitElement`. Улучшит читабельность кода. Не критично

2022-04-09 09:20 UTC, vitali-usik commented on js/form-init.js
> +      // не срабатывает разблокировка кнопки
Это комментарий для меня что что-то не работает?

2022-04-09 09:20 UTC, vitali-usik commented on js/form-init.js
> +const initializeForm = () => {
Между комментарием-описанием метода не нужна пустая строка что бы не путаться

2022-04-09 09:20 UTC, vitali-usik commented on js/form-upload-close.js
> +function openImgOverlay() {
Выше по коду были использованы стрелочные функции, здесь function declaration. Ошибка или есть какой-то скрытый смысл?

2022-04-09 09:20 UTC, vitali-usik commented on js/messages.js
> +function onSuccessErrorEscKeydown(evt) {
Смотри комментарий выше про функции

2022-04-09 09:20 UTC, vitali-usik commented on js/form-init.js
> +    if (isPristineValid) {
Здесь проверяется значение переменной. Она всегда будет равна `false` потому что в нее записан результат выполнения кода `const isPristineValid = pristine.validate();` Нам же нужно каждый раз динамически это проверять. Соответственно меняем код на `const isPristineValid = () => pristine.validate();` и в условии вызываем эту функцию `if (isPristineValid()) {`

2022-04-11 20:34 UTC, Kirkusik commented
http://joxi.ru/L21MEgOCw0OG42 - непонятные дополнительные поля. Их не должно быть.
http://joxi.ru/zANx97oU1jZJpm - уменьшение/увеличение должно применяться не ко всему контейнеру, а только к картинке.

2022-04-11 20:34 UTC, closed without merging